env                   = "dev"
aws-region            = "eu-central-1"
vpc-cidr-block        = "10.16.0.0/16"
vpc-name              = "testing-vpc"
igw-name              = "testing-igw"
pub-subnet-count      = 3
pub-cidr-block        = ["10.16.0.0/20", "10.16.16.0/20", "10.16.32.0/20"]
pub-availability-zone = ["eu-central-1a", "eu-central-1b", "eu-central-1c"]
pub-sub-name          = "testing-subnet-public"
pri-subnet-count      = 3
pri-cidr-block        = ["10.16.128.0/20", "10.16.144.0/20", "10.16.160.0/20"]
pri-availability-zone = ["eu-central-1a", "eu-central-1b", "eu-central-1c"]
pri-sub-name          = "testing-subnet-private"
public-rt-name        = "testing-public-route-table"
private-rt-name       = "testing-private-route-table"
eip-name              = "testing-elasticip-ngw"
ngw-name              = "testing-ngw"
eks-sg                = "testing-eks-sg"